import * as fs from 'fs/promises';
import * as path from 'path';
import { nanoid } from 'nanoid';
import * as child_process from 'child_process';
import { promisify } from 'util';

const exec = promisify(child_process.exec);

interface NodeDefinition {
  id: string;
  type: string;
  name: string;
  x: number;
  y: number;
  inputs?: Record<string, any>;
  parameters?: Record<string, any>;
  flags?: string[];
  children?: NodeDefinition[];
}

interface ConnectionDefinition {
  from: string;
  fromOutput?: number;
  to: string;
  toInput?: number;
}

interface ProjectSpec {
  nodes: NodeDefinition[];
  connections: ConnectionDefinition[];
  globals?: Record<string, any>;
  perform?: {
    resolution: string;
    fps: number;
    realtime: boolean;
  };
  summary?: Record<string, any>;
}

export class TOEGeneratorFixed {
  private nodeCounter = 0;
  private projectPath: string;
  private touchDesignerPath: string;
  private templatesPath: string;

  constructor(projectPath?: string) {
    this.projectPath = projectPath || process.env.TD_PROJECT_PATH || 'C:/Users/talla/Documents/touchdesigner-projects';
    this.touchDesignerPath = process.env.TD_INSTALL_PATH || 'C:/Program Files/Derivative/TouchDesigner/bin';
    this.templatesPath = path.join(this.projectPath, '_templates');
  }

  async createProject(name: string, spec: ProjectSpec): Promise<string> {
    const projectDir = path.join(this.projectPath, name);
    await fs.mkdir(projectDir, { recursive: true });
    
    // Generate Python script that TouchDesigner will execute
    const pythonScript = this.generatePythonScript(name, spec);
    const scriptPath = path.join(projectDir, `${name}_generator.py`);
    await fs.writeFile(scriptPath, pythonScript);
    
    // Create the project file path
    const projectFile = path.join(projectDir, `${name}.toe`);
    
    // Method 1: Use TouchDesigner CLI to execute the script
    try {
      const tdExecutable = path.join(this.touchDesignerPath, 'TouchDesigner.exe');
      
      // First, create an empty project using TouchDesigner
      const createProjectScript = `
import td

# Save empty project
project.save('${projectFile.replace(/\\/g, '/')}')

# Now run the generator script
td.run('${scriptPath.replace(/\\/g, '/')}')
`;
      
      const tempScriptPath = path.join(projectDir, 'create_empty.py');
      await fs.writeFile(tempScriptPath, createProjectScript);
      
      // Execute TouchDesigner in background mode to create the project
      await exec(`"${tdExecutable}" -nogui "${tempScriptPath}"`);
      
      // Clean up temp file
      await fs.unlink(tempScriptPath);
      
    } catch (error) {
      console.error('Failed to create project via TouchDesigner CLI:', error);
      
      // Method 2: Create a starter template if CLI fails
      await this.createStarterTemplate(projectFile);
      
      // Save the Python script for manual execution
      console.log(`Python script saved to: ${scriptPath}`);
      console.log('Open the project in TouchDesigner and run the script manually');
    }
    
    return projectFile;
  }

  private generatePythonScript(name: string, spec: ProjectSpec): string {
    const lines: string[] = [
      '"""',
      `TouchDesigner Project Generator Script for ${name}`,
      'Generated by TouchDesigner MCP Server',
      '"""',
      '',
      'import td',
      '',
      '# Clear the network',
      'root = op("/")',
      'for child in root.children:',
      '    if child.name not in ["local", "perform", "project1"]:',
      '        child.destroy()',
      '',
      '# Configure project settings',
      this.generatePerformSettings(spec.perform),
      '',
      '# Create nodes',
      'nodes = {}',
      ''
    ];

    // Generate node creation code
    spec.nodes.forEach(node => {
      lines.push(...this.generateNodeCreation(node));
    });

    lines.push('', '# Create connections');
    
    // Generate connection code
    spec.connections.forEach(conn => {
      lines.push(this.generateConnection(conn));
    });

    lines.push('', '# Save project', 'project.save()', '', 'print("Project generated successfully!")');
    
    return lines.join('\n');
  }

  private generatePerformSettings(perform?: ProjectSpec['perform']): string {
    const settings = {
      resolution: '1920x1080',
      fps: 60,
      realtime: true,
      ...perform
    };
    
    const [width, height] = settings.resolution.split('x');
    
    return `
# Performance settings
op.perform.par.resolution1 = ${width}
op.perform.par.resolution2 = ${height}
op.perform.par.rate = ${settings.fps}
op.perform.par.realtime = ${settings.realtime ? 1 : 0}
`;
  }

  private generateNodeCreation(node: NodeDefinition, parentPath: string = '/'): string[] {
    const lines: string[] = [];
    const varName = `node_${node.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
    
    // Create the node
    lines.push(`# Create ${node.name}`);
    lines.push(`${varName} = op('${parentPath}').create(${node.type}, '${node.name}')`);
    lines.push(`${varName}.nodeX = ${node.x}`);
    lines.push(`${varName}.nodeY = ${node.y}`);
    lines.push(`nodes['${node.name}'] = ${varName}`);
    
    // Set parameters
    if (node.parameters) {
      lines.push('# Set parameters');
      Object.entries(node.parameters).forEach(([param, value]) => {
        if (typeof value === 'string') {
          lines.push(`${varName}.par.${param} = '${value}'`);
        } else {
          lines.push(`${varName}.par.${param} = ${value}`);
        }
      });
    }
    
    // Create children
    if (node.children && node.children.length > 0) {
      lines.push('# Create children');
      node.children.forEach(child => {
        lines.push(...this.generateNodeCreation(child, `${parentPath}${node.name}/`));
      });
    }
    
    lines.push('');
    return lines;
  }

  private generateConnection(conn: ConnectionDefinition): string {
    const fromOutput = conn.fromOutput || 0;
    const toInput = conn.toInput || 0;
    
    return `nodes['${conn.to}'].inputConnectors[${toInput}].connect(nodes['${conn.from}'].outputConnectors[${fromOutput}])`;
  }

  private async createStarterTemplate(projectFile: string): Promise<void> {
    // Create a minimal valid TouchDesigner project structure
    // This would ideally use a pre-made template .toe file
    
    const templatePath = path.join(this.templatesPath, 'blank.toe');
    
    try {
      // Check if we have a template
      await fs.access(templatePath);
      await fs.copyFile(templatePath, projectFile);
    } catch {
      // If no template exists, we'll need to document this limitation
      console.warn('No template file found. TouchDesigner must create the initial .toe file.');
      
      // Create a README explaining the issue
      const readmePath = path.join(path.dirname(projectFile), 'README_TOE_CREATION.txt');
      await fs.writeFile(readmePath, `
IMPORTANT: TouchDesigner Project Creation

The MCP server cannot directly create valid .toe files because they are
proprietary binary formats, not simple compressed XML.

To create your project:

1. Open TouchDesigner
2. Create a new empty project
3. Save it as: ${path.basename(projectFile)}
4. Run the generator script: ${path.basename(projectFile, '.toe')}_generator.py

The generator script contains all the nodes and connections for your project
and will build it automatically when executed in TouchDesigner.

This is a limitation of the TouchDesigner file format, not the MCP server.
`);
    }
  }

  // Helper methods remain the same but return Python code strings instead
  
  createConstantTOPCode(name: string, resolution: string = '1920x1080', color: string = '0 0 0 1'): string {
    const [r, g, b, a] = color.split(' ');
    const [w, h] = resolution.split('x');
    
    return `
# Create Constant TOP
constant_${name} = op('/').create(constantTOP, '${name}')
constant_${name}.par.resolutionw = ${w}
constant_${name}.par.resolutionh = ${h}
constant_${name}.par.colorr = ${r}
constant_${name}.par.colorg = ${g}
constant_${name}.par.colorb = ${b}
constant_${name}.par.colora = ${a}
`;
  }

  createKinectTOPCode(name: string): string {
    return `
# Create Kinect TOP
kinect_${name} = op('/').create(kinect2TOP, '${name}')
kinect_${name}.par.player = 0  # First Kinect device
kinect_${name}.par.image = 'depth'
kinect_${name}.par.depthformat = 'meters'
kinect_${name}.par.depthrange1 = 0.5
kinect_${name}.par.depthrange2 = 4.0
`;
  }

  createParticleSOPCode(name: string): string {
    return `
# Create Particle SOP
particles_${name} = op('/').create(particleSOP, '${name}')
particles_${name}.par.birthrate = 100
particles_${name}.par.life = 2.0
particles_${name}.par.lifev = 0.5
particles_${name}.par.const = 0  # Use input for positions
`;
  }
}